language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - "$HOME/.npm"
before_install:
- openssl aes-256-cbc -K $encrypted_2f2f1b9d8185_key -iv $encrypted_2f2f1b9d8185_iv
  -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install --non-interactive --pure-lockfile --frozen-lockfile --production=false
script:
- ember test
deploy:
- skip_cleanup: true
  provider: "./.travis/deploy-dev.sh"
  on:
    branch: develop
