---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive --pure-lockfile --frozen-lockfile --production=false

after_success:
  tar -czf dist.tgz dist

  if [ "$TRAVIS_BRANCH" = "develop" -o -n "$TRAVIS_TAG" ]; then
    scp dist.tgz $DEPLOY_USER_DEV@$DEPLOY_HOST_DEV:$DEPLOY_PATH_DEV
    ssh $DEPLOY_USER_DEV@$DEPLOY_HOST_DEV "~/bin/deploy.sh > ~/log/deploy.log";
  fi;
